// projects.js
export const projects = [
  {
    id: 1,
    title: "Tvoja Pomoć",
    description:
      "This comprehensive e-commerce solution encompasses two distinct interfaces: an intuitive online shop for customers and a robust admin panel for managing the business. The platform is designed to streamline the shopping experience while providing administrators with powerful tools for oversight and management.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      { name: "TypeScript", icon: "SiTypescript", color: "text-blue-400" },
      { name: "React", icon: "FaReact", color: "text-blue-500" },
      { name: "Next.js", icon: "SiNextdotjs", color: "text-black invert" },
      { name: "MongoDB", icon: "SiMongodb", color: "text-green-500" },
      {
        name: "Shadcn/ui",
        icon: "SiShadcnui",
        color: "bg-white text-black rounded-md p-2",
      },
      { name: "TailwindCSS", icon: "SiTailwindcss", color: "text-blue-400" },
      { name: "Clerk", icon: "SiClerk", color: "text-teal-200" },
      { name: "Cloudinary", icon: "SiCloudinary", color: "text-white" },
    ],
    link: "https://tvojapomoc.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/tvojapomoc",
    monitorUrl: "https://tvojapomoc.vercel.app/",
    mobileImg: "/img/websites/tpMobile.png",
    monitorImg: "/img/websites/tpMonitor.webp",
    phoneUrl: "https://tvojapomoc.vercel.app/",
    imageUrl: "/img/websites/tp.png",
    onlyMobile: false,
  },
  {
    id: 2,
    title: "E-commerce Admin and Store System",
    description:
      "This comprehensive e-commerce solution encompasses two distinct interfaces: an intuitive online shop for customers and a robust admin panel for managing the business. The platform is designed to streamline the shopping experience while providing administrators with powerful tools for oversight and management.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      { name: "TypeScript", icon: "SiTypescript", color: "text-blue-400" },
      { name: "React", icon: "FaReact", color: "text-blue-500" },
      { name: "Next.js", icon: "SiNextdotjs", color: "text-black invert" },
      { name: "MongoDB", icon: "SiMongodb", color: "text-green-500" },
      {
        name: "Shadcn/ui",
        icon: "SiShadcnui",
        color: "bg-white text-black rounded-md p-2",
      },
      { name: "TailwindCSS", icon: "SiTailwindcss", color: "text-blue-400" },
      { name: "NextAuth.js", icon: "SiNextdns", color: "text-teal-200" },
      { name: "Cloudinary", icon: "SiCloudinary", color: "text-white" },
      {
        name: "Stripe",
        icon: "FaCcStripe",
        color: " text-[rgb(109,101,252)] ",
      },
    ],
    link: "https://ecom-front-coja.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/ecomFront",
    monitorUrl: "https://ecom-front-coja.vercel.app/",
    phoneUrl: "https://ecom-front-coja.vercel.app/",
    mobileImg: "/img/websites/ecomMobile.webp",
    monitorImg: "/img/websites/ecomMonitor.webp",
    imageUrl: "/img/websites/ecom.png",
    onlyMobile: false,
  },
  {
    id: 3,
    title: "Restorani Subotica",
    description:
      "Restorani Subotica is a meticulously crafted web application that curates an extensive list of restaurants in Subotica. Designed with both locals and tourists in mind, this project offers a user-friendly platform to explore dining options in the city.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "TypeScript", icon: "SiTypescript", color: "text-blue-400" },
      { name: "React", icon: "FaReact", color: "text-blue-500" },
      { name: "Next.js", icon: "SiNextdotjs", color: "text-black invert" },
      { name: "TailwindCSS", icon: "SiTailwindcss", color: "text-blue-400" },
    ],
    link: "https://restorani-subotica.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/Restorani_Subotica2",
    monitorUrl: "https://restorani-subotica.vercel.app/",
    phoneUrl: "https://restorani-subotica.vercel.app/",
    mobileImg: "/img/websites/restmobile.png",
    monitorImg: "/img/websites/resMonitor.webp",
    imageUrl: "/img/websites/res.png",
    onlyMobile: false,
  },

  {
    id: 4,
    title: "Amedia Studio",
    description:
      "Amedia Studio is a dynamic and visually captivating landing page designed to showcase the creative and technical services of a cutting-edge media studio. Specializing in website development, design, and various multimedia solutions, Amedia Studio aims to attract potential clients with an engaging online presence.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      { name: "React", icon: "FaReact", color: "text-blue-500" },
      { name: "Next.js", icon: "SiNextdotjs", color: "text-black invert" },
      { name: "Three.js", icon: "SiThreedotjs", color: "text-black invert" },
      { name: "TailwindCSS", icon: "SiTailwindcss", color: "text-blue-400" },
    ],
    link: "https://amedia-five.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/Amedia",
    monitorUrl: "https://amedia-five.vercel.app/",
    phoneUrl: "https://amedia-five.vercel.app/",
    imageUrl: "/img/websites/amedia.png",
    mobileImg: "/img/websites/amediaMobile.webp",
    monitorImg: "/img/websites/amediaMonitor.webp",
    onlyMobile: false,
  },
  {
    id: 5,
    title: "Windows Portfolio",
    description:
      "This project is a web-based portfolio designed to mimic the look and feel of the Windows operating system. It includes a start menu, desktop, and interactive apps that showcase your projects, resume, and contact information in a unique and nostalgic way.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      { name: "React", icon: "FaReact", color: "text-blue-500" },
      { name: "Next.js", icon: "SiNextdotjs", color: "text-black invert" },
      { name: "TailwindCSS", icon: "SiTailwindcss", color: "text-blue-400" },
    ],
    link: "https://windows-portfolio-v2.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/WindowsPortfolioV2",
    monitorUrl: "https://windows-portfolio-v2.vercel.app/",
    phoneUrl: "https://windows-portfolio-v2.vercel.app/",
    mobileImg: "/img/websites/wpMobile.webp",
    monitorImg: "/img/websites/wpMonitor.webp",
    imageUrl: "/img/websites/ecom.png",
    onlyMobile: false,
  },
  {
    id: 5,
    title: "InstaGrid Creator",
    description:
      "InstaGrid Creator is a web-based tool that allows users to easily create multi-image Instagram posts with customizable layouts. This project aims to simplify the process of creating visually appealing grid layouts for Instagram, providing users with various options to arrange their images and adjust the appearance of their posts.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      { name: "DOM to Image", icon: "GrDomain", color: "text-blue-500" },
    ],
    link: "https://instagridcreator.vercel.app/",
    gitHubLink: "https://github.com/CojaDev/InstaGrid-Creator",
    monitorUrl: "https://instagridcreator.vercel.app/",
    phoneUrl: "https://instagridcreator.vercel.app/",
    mobileImg: "/img/websites/igMobile.webp",
    monitorImg: "/img/websites/igMonitor.webp",
    imageUrl: "/img/websites/ig.png",
    onlyMobile: false,
  },
  {
    id: 7,
    title: "Calorie Mobile App",
    description:
      "This Android app helps users manage their diet by tracking calorie intake and calculating BMI. Users can log meals, see calories consumed and remaining, and use a comprehensive food table to calculate calories for different portion sizes. Built with React Native, the app supports healthier eating habits with a user-friendly interface.",
    technologies: [
      { name: "HTML5", icon: "FaHtml5", color: "text-orange-600" },
      { name: "CSS3", icon: "FaCss3Alt", color: "text-blue-600" },
      { name: "JavaScript", icon: "FaJsSquare", color: "text-yellow-500" },
      {
        name: "React Native",
        icon: "TbBrandReactNative",
        color: "text-white",
      },
      { name: "Expo", icon: "SiExpo", color: "text-white text-[2.05rem]" },
    ],
    link: "https://github.com/CojaDev/Calorie-App-for-Mobile",
    gitHubLink: "https://github.com/CojaDev/WindowsPortfolioV2",
    monitorUrl: "",
    phoneUrl: "",
    mobileImg: "",
    monitorImg: "",
    imageUrl: "/img/websites/cal.png",
    onlyMobile: true,
  },
];
